
#Storage Settings
[storage]
	#The amount of slots the storage stabilizer tier 1 provides.
	stabilizerTier1Slots = 128
	#The amount of slots the storage stabilizer tier 3 provides.
	stabilizerTier3Slots = 512
	#The amount of slots the storage stabilizer tier 2 provides.
	stabilizerTier2Slots = 256
	#The amount of slots the storage actuator provides.
	controllerBaseSlots = 128
	#The amount of slots the storage stabilizer tier 4 provides.
	stabilizerTier4Slots = 1024

#WorldGen Settings
[worldgen]

	#Ore Gen Settings
	[worldgen.oregen]

		#Ore Settings
		[worldgen.oregen.otherstoneNatural]
			#The dimensions this ore will spawn in.
			dimensionWhitelist = ["overworld"]
			#The size of veins for this ore.
			#Range: 0 ~ 127
			oreSize = 7
			#The chance (amount of rolls) for this ore to spawn.
			#Range: 0 ~ 127
			oreChance = 5
			#The type of block this ore will spawn in.
			fillerBlockType = "natural_stone"
			#The maximum height for this ore veins to spawn.
			oreMax = 80
			#The minimum height for this ore veins to spawn.
			oreMin = 10

		#Ore Settings
		[worldgen.oregen.iesniumOre]
			#The dimensions this ore will spawn in.
			dimensionWhitelist = ["the_nether"]
			#The size of veins for this ore.
			#Range: 0 ~ 127
			oreSize = 3
			#The chance (amount of rolls) for this ore to spawn.
			#Range: 0 ~ 127
			oreChance = 10
			#The type of block this ore will spawn in.
			fillerBlockType = "netherrack"
			#The maximum height for this ore veins to spawn.
			oreMax = 128
			#The minimum height for this ore veins to spawn.
			oreMin = 10

		#Ore Settings
		[worldgen.oregen.copperOre]
			#The dimensions this ore will spawn in.
			dimensionWhitelist = ["overworld"]
			#The size of veins for this ore.
			#Range: 0 ~ 127
			oreSize = 9
			#The chance (amount of rolls) for this ore to spawn.
			#Range: 0 ~ 127
			oreChance = 20
			#The type of block this ore will spawn in.
			fillerBlockType = "natural_stone"
			#The maximum height for this ore veins to spawn.
			oreMax = 64
			#The minimum height for this ore veins to spawn.
			oreMin = 20

		#Ore Settings
		[worldgen.oregen.silverOre]
			#The dimensions this ore will spawn in.
			dimensionWhitelist = ["overworld"]
			#The size of veins for this ore.
			#Range: 0 ~ 127
			oreSize = 7
			#The chance (amount of rolls) for this ore to spawn.
			#Range: 0 ~ 127
			oreChance = 5
			#The type of block this ore will spawn in.
			fillerBlockType = "natural_stone"
			#The maximum height for this ore veins to spawn.
			oreMax = 30
			#The minimum height for this ore veins to spawn.
			oreMin = 0

	#Underground Grove Settings
	[worldgen.underground_grove]
		#The chance vines will spawn in the underground grove.
		vineChance = 0.3
		#The dimensions whitelisted for underground grove generation.
		dimensionWhitelist = ["overworld"]
		#The min height for a grove to spawn (applied to the center of the grove, not the floor).
		groveSpawnMin = 25
		#The max height for a grove to spawn (applied to the center of the grove, not the ceiling).
		groveSpawnMax = 60
		#The chance glowstone will spawn in the ceiling of the underground grove.
		ceilingLightChance = 0.1
		#The chance for a grove to spawn in a chunk (generates 1/groveSpawnChance chunks on average).
		groveSpawnChance = 400
		#The chance small trees will spawn in the underground grove.
		treeChance = 0.1
		#The biome types to spawn underground groves in.
		validBiomes = ["JUNGLE", "LUSH", "PLAINS", "FOREST", "CONIFEROUS", "MAGICAL"]
		#The chance grass will spawn in the underground grove.
		grassChance = 0.6

#Ritual Settings
[rituals]
	#Enables the ritual to start a thunderstorm.
	enableThunderWeatherRitual = true
	#Enables the ritual to set time to day.
	enableDayTimeRitual = true
	#Enables the ritual to set time to night.
	enableNightTimeRitual = true
	#Enables the ritual to start rainy weather.
	enableRainWeatherRitual = true
	#Enables the ritual to clear rainy weather.
	enableClearWeatherRitual = true

#Dimensional Mineshaft Settings
[dimensional_mineshaft]

	#Miner Spirit Settings
	[dimensional_mineshaft.miner_djinni_ores]
		#The amount of blocks the spirit will obtain per mining operation
		rollsPerOperation = 1
		#The amount of mining operations the spirit can perform before breaking.
		durability = 100
		#The amount of time it takes the spirit to perform one mining operation.
		maxMiningTime = 400

	#Miner Spirit Settings
	[dimensional_mineshaft.miner_foliot_unspecialized]
		#The amount of blocks the spirit will obtain per mining operation
		rollsPerOperation = 1
		#The amount of mining operations the spirit can perform before breaking.
		durability = 1000
		#The amount of time it takes the spirit to perform one mining operation.
		maxMiningTime = 400

