
[general]
	#The module blacklist of this material.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 10523541
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "metallic"
	#Should items of this material have the enchanted glow.
	hasEffect = false

[silents_mechanisms]
	#The byproduct material to output in Silent's Mechanisms' Crusher.
	byproduct = "minecraft:cobblestone"

[create]
	#The byproduct material to output in Create's crushing.
	byproduct = "minecraft:cobblestone"

[crossroads]
	#The byproduct material to output in Crossroads' Millstone.
	byproduct = "minecraft:sand"

[indreb]
	#The byproduct material to output in Industrial Reborn's crushing.
	byproduct = "minecraft:cobblestone"

[mekanism]
	#The base to use in Mekanism's Combiner to recreate ores.
	ore_base = "#forge:cobblestone"

